### ISSUE TITLE
import error for theano when installing with pip

### ISSUE THREAD

**Issue by janfb** [mackelab/delfi#17]
starting from scrath in a new anaconda env the installation with `pip` works fine. However, going through`getting started` with inference on the 1D Gaussian the inference does not work because upon importing `lasagne` the `NeuralNet` throws an `ImportError` on 

`from theano.tensor.signal import downsample`

I think this is due to this: [https://github.com/aigamedev/scikit-neuralnetwork/issues/235](https://github.com/aigamedev/scikit-neuralnetwork/issues/235)
So there seems to be a mismatch between `theano` and `lasagne`. 

I also noted that the installation with `pip` actually installs `lasagne 0.1`: 

> Successfully built delfi dill lasagne theano
Installing collected packages: dill, numpy, lasagne, scipy, six, theano, tqdm, delfi
Successfully installed delfi-0.3.2 dill-0.2.7.1 lasagne-0.1 numpy-1.13.3 scipy-1.0.0 six-1.11.0 theano-0.9.0 tqdm-4.19.4

However, the requirements ([link)](http://www.mackelab.org/delfi/installation.html) say that `delfi` is using `lasagne0.2dev`.

**Comment by janfb** [comment]
One potential fix is to downgrade `theano` to `0.8.2`. Then the `Getting started` and inference on the `balancednetwork` work.

**Comment by kaandocal** [comment]
Another option (which I tried for the lab computer) is to pull a newer (development) version of lasagne. This will be more suitable for people who might want to use a more up-to-date version of theano.

**Comment by jan-matthis** [comment]
Thanks for documenting this! In line with what @kaandocal writes, I'd recommend installing the development version of lasagne manually and using an up-to-date theano version. 

When installing using `setup.py` rather than pip, this will happen automatically due to the dependency link specified here:
https://github.com/mackelab/delfi/blob/master/setup.py#L19 

Will look into how to archive this when installing through pip

**Comment by jan-matthis** [comment]
As an interim solution when using pip, this should work
```
pip install delfi --process-dependency-links
```

Not perfectly happy with this since it requires an extra flag. In addition, dependency links might be removed from pip in the future (https://github.com/pypa/pip/issues/4187)

**Comment by janfb** [comment]
installing the `lasagne dev2` version manually works as a solution only when I clone `delfi` and install via `setup.py` not when using pip. 

The fix with the extra flag works fine.

**Comment by teran-mckinney** [comment]
What's the proper workflow for this?

Let 's say there's a library that I need to add a feature to. I fork it on Github. Feature isn't going to be merged any time soon, so I have a tool that I set to use my Github fork instead of PyPi.

Now all of my users have to add --process-dependency-links when installing my tool with pip, which is a deprecated and even once removed flag?

Is there some option in setup.py that I'm missing or is there really no way around this? It seems like the only viable way to do this is to push up a forked pypi package. That is just going to add to user's confusion once your pull request does get merged, anyway.

**Comment by jan-matthis** [comment]
Closing, will stick to `--process-dependency-links` for now.
